CREATE TABLE IF NOT EXISTS weekly_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    week_start TEXT NOT NULL,
    week_end TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    weight_start REAL,
    weight_end REAL,
    weight_delta REAL,
    avg_calories REAL,
    avg_protein REAL,
    avg_carbs REAL,
    avg_fat REAL,
    waist_delta REAL,
    adherence_score REAL,
    trend_status TEXT,
    weekly_weight_delta REAL,
    moving_average_latest REAL,
    plateau_detected INTEGER DEFAULT 0,
    recommendation TEXT,
    notes TEXT,
    score REAL,
    summary TEXT
);
